Update index.d.ts
fastify/middie pull request #202
Opened 2024-06-14 08:34 UTC by juliusmarminge

excuse me if this is invalid but from reading the examples it seems like async functions are allowed, so the return type should accept a promise?

2024-06-14 09:24 UTC, mcollina commented
What examples? Are those on our website?

You really _should not_ use `async` here, nor in most other middleware, because there is no real error handling for rejecting promises. Nor there is in express or connect etc.

In essence, the types are telling you that what you are doing is essentially unsafe, because it is.

2024-09-11 07:37 UTC, Uzlopak commented
In express v4 I needed to use this one "hack" where you could have async handlers. I think express v5 has native async handler support.

2024-09-26 16:07 UTC, mcollina requested changes
Unfortunately we do not handle promises here. A rejection in one of those promise would lead to a `unhandledRejection`, therefore making it problematic. We could support this, but work to add it should be done to library, not just the types.

2024-11-22 05:29 UTC, Vue-Pu approved these changes

2025-04-15 08:51 UTC, Fdawgs commented
Closing due to discussion above re extra work needed, and no activity.

2025-04-15 08:51 UTC, closed without merging